package net.alienminds.ethnogram.ui.theme

import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val lightScheme = lightColorScheme(
    primary = AppColor.blue700,
    onPrimary = AppColor.white,
    primaryContainer = AppColor.blue50,
    onPrimaryContainer = AppColor.blue800,
    secondary = AppColor.brown500,
    onSecondary = AppColor.white,
    secondaryContainer = AppColor.brown100,
    onSecondaryContainer = AppColor.brown900,
    tertiary = AppColor.blueGray500,
    onTertiary = AppColor.white,
    tertiaryContainer = AppColor.blueGray100,
    onTertiaryContainer = AppColor.blueGray900,
    error = AppColor.red700,
    onError = AppColor.white,
    errorContainer = AppColor.red100,
    onErrorContainer = AppColor.red900,
    background = AppColor.brown10,
    onBackground = AppColor.black,
    surface = AppColor.brown50,
    onSurface = AppColor.black,
    surfaceVariant = AppColor.gray200,
    onSurfaceVariant = AppColor.gray700,
    outline = AppColor.gray600,
    outlineVariant = AppColor.gray400,
    scrim = AppColor.black,
    inverseSurface = AppColor.brown700,
    inverseOnSurface = AppColor.white,
    inversePrimary = AppColor.blue300,
    surfaceDim = AppColor.brown200,
    surfaceBright = AppColor.brown50,
    surfaceContainerLowest = AppColor.white,
    surfaceContainerLow = AppColor.brown50,
    surfaceContainer = AppColor.gray100,
    surfaceContainerHigh = AppColor.brown200,
    surfaceContainerHighest = AppColor.brown300,
)
